Update Dockerfile

diff --git a/php-fpm/7.4/Dockerfile b/php-fpm/7.4/Dockerfile
--- a/php-fpm/7.4/Dockerfile
+++ b/php-fpm/7.4/Dockerfile
@@ -57,35 +57,34 @@ RUN set -eux; \
 
 SHELL ["/bin/ash", "-eo", "pipefail", "-c"]
 # hadolint ignore=DL3003
-RUN set -eux; \
-  apk add --no-cache --virtual .fetch-deps gnupg=2.2.19-r0; \
-  \
-  mkdir -p /usr/src; \
-  cd /usr/src; \
-  \
-  curl -fSL --retry 5 -o php.tar.xz "$PHP_URL"; \
-  \
-  if [ -n "$PHP_SHA256" ]; then \
-    echo "$PHP_SHA256 *php.tar.xz" | sha256sum -c -; \
-  fi; \
-  if [ -n "$PHP_MD5" ]; then \
-    echo "$PHP_MD5 *php.tar.xz" | md5sum -c -; \
-  fi; \
-  \
-  if [ -n "$PHP_ASC_URL" ]; then \
-    curl -fSL --retry 5 -o php.tar.xz.asc "$PHP_ASC_URL"; \
-    GNUPGHOME="$(mktemp -d)"; \
-    export GNUPGHOME; \
-    for key in $GPG_KEYS; do \
-      echo "$key"; \
-#       gpg --batch --keyserver ha.pool.sks-keyservers.net --recv-keys "$key"; \
-    done; \
-    gpg --batch --verify php.tar.xz.asc php.tar.xz; \
-    gpgconf --kill all; \
-    rm -rf "$GNUPGHOME"; \
-  fi; \
-  \
-  apk del --no-network .fetch-deps
+# RUN set -eux; \
+#   apk add --no-cache --virtual .fetch-deps gnupg=2.2.19-r0; \
+#   \
+#   mkdir -p /usr/src; \
+#   cd /usr/src; \
+#   \
+#   curl -fSL --retry 5 -o php.tar.xz "$PHP_URL"; \
+#   \
+#   if [ -n "$PHP_SHA256" ]; then \
+#     echo "$PHP_SHA256 *php.tar.xz" | sha256sum -c -; \
+#   fi; \
+#   if [ -n "$PHP_MD5" ]; then \
+#     echo "$PHP_MD5 *php.tar.xz" | md5sum -c -; \
+#   fi; \
+#   \
+#   if [ -n "$PHP_ASC_URL" ]; then \
+#     curl -fSL --retry 5 -o php.tar.xz.asc "$PHP_ASC_URL"; \
+#     GNUPGHOME="$(mktemp -d)"; \
+#     export GNUPGHOME; \
+#     for key in $GPG_KEYS; do \
+#        gpg --batch --keyserver ha.pool.sks-keyservers.net --recv-keys "$key"; \
+#     done; \
+#     gpg --batch --verify php.tar.xz.asc php.tar.xz; \
+#     gpgconf --kill all; \
+#     rm -rf "$GNUPGHOME"; \
+#   fi; \
+#   \
+#   apk del --no-network .fetch-deps
 
 
 # hadolint ignore=SC2046,SC2086,DL3003,DL3018
